### PR TITLE
More filters

### PR DESCRIPTION
**Pull request by GhostShot3**
- [x] Ready to merge

### CODE REVIEW

**Comment by Podshot** [comment]
@GhostShot3 These filters are all made by Sethbling. I appreciate you wanting to contribute to this repository, but they need to either original filters, or improvements on existing ones, while the filters you are committing here are just plain copies.

**Comment by GhostShot3** [comment]
Desistalar mitosis.

**Comment by Podshot** [comment]
May I ask what that has to do with or contribute to your pull request? If you spam this thread with unneeded nonsense, this thread will be locked

**Comment by GhostShot3** [comment]
@Podshot Sorry I did not mean to.

**Comment by GhostShot3** [comment]
@Podshot Hey want to help im making Filters too

**Pull request closed without merging**
